# Generated by Django 2.1.7 on 2019-03-05 14:34

from django.db import migrations
from similar.models import Course

from django.db import transaction

import os

FILE = os.path.abspath(os.path.join(os.path.dirname(__file__), 'data', 'courses.txt'))


@transaction.non_atomic_requests
def migrate(*args):
    with open(FILE, 'r') as file:
        for line in file.readlines():
            course = Course(name=line).save()



def reverse(*args):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('similar', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate, reverse)
    ]
