# Generated by Django 2.1.7 on 2019-03-11 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('similar', '0003_auto_20190305_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeraValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1_values', to='similar.User')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2_values', to='similar.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='meravalue',
            unique_together={('user_1', 'user_2')},
        ),
    ]
